baseURL = "https://mchan1970.github.io/personal-blog/"
languageCode = "zh-cn"
title = "Voice"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "é¦–é¡µ"
    url = "/"
    weight = 5
  [[menu.main]]
    name = "äº”åƒå¹´æ¶æ„å¸ˆ"
    url = "/5000-architect/"
    weight = 10
  [[menu.main]]
    name = "ä¸šä¸»ç»´æƒ"
    url = "/property-rights/"
    weight = 20

[taxonomies]
  tag = "tags"
  series = "series"

[params]
  author = "é™ˆé€¸å³°"
  DateFormat = "2006å¹´1æœˆ2æ—¥"
  disableSpecial1stPost = true
  mainSections = ["5000-architect", "property-rights"]

  # å¼€å¯ä¸»é¡µåç‰‡æ¨¡å¼
  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = "Hi, this is Chen Yifeng. I blog to think about interesting things."
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
    [markup.goldmark.extensions]
      typographer = false

[pagination]
  pagerSize = 8
